services:
  db:
    image: postgres:latest
    container_name: skillin-db
    environment:
      POSTGRES_DB: "skillin-db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5433:5432"
    volumes:
      - skillin-pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  skillin-pgdata:
